<?php
/**
 * Magento e-commerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 *
 * @category   Losreservas1811
 * @package    Losreservas1811_Sales
 * @copyright  Copyright (c) 2018 LOS RESERVAS 1811, SL (https://www.losreservas1811.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 *
 * @category   design
 * @package    base_default/losreservas1811_sales
 * @author     LOS RESERVAS 1811 Team <web@losreservas1811.com>
 */
?>
<?php
/**
 * Sales Order Recent template
 *
 * @see Mage_Sales_Block_Order_Recent
 */
?>
<div class="box-account box-recent">
<?php $_orders = $this->getOrders(); ?>
    <div class="box-head">
        <h2><?php echo $this->__('Recent Orders') ?></h2>
        <?php if( sizeof($_orders->getItems()) > 0 ): ?><a href="<?php echo $this->getUrl('sales/order/history') ?>"><?php echo $this->__('View All') ?></a><?php endif; ?>
    </div>
<?php if( sizeof($_orders->getItems()) > 0 ): ?>
    <table class="data-table orders" id="my-orders-table">
    <col width="1" />
    <col width="1" />
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
        <thead>
            <tr>
                <th><?php echo Mage::helper('losreservas1811_sales')->__('Order #') ?></th>
                <th class="date"><?php echo $this->__('Date') ?></th>
                <th class="ship"><?php echo $this->__('Ship To') ?></th>
                <th class="total"><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
                <th class="status"><?php echo $this->__('Status') ?></th>
                <th class="view">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($_orders as $_order): ?>
                <tr>
                    <td><?php echo $_order->getRealOrderId() ?></td>
                    <td class="date"><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                    <td class="ship"><?php echo $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                    <td class="total"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td class="status"><em><?php echo $_order->getStatusLabel() ?></em></td>
                    <td class="a-left view">
                        <span class="nobr">
                        <!--<a href="<?php echo $this->getViewUrl($_order) ?>"><?php //echo $this->__('View Order') ?></a>//-->
                        <a href="<?php echo $this->getViewUrl($_order) ?>" title="<?php echo $this->__('View Order') ?>">
                            <span class="fa fa-2x fa-file-text-o"></span>
                        </a>
                        <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                            <!--<span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>//-->
                        <?php endif ?>
                        <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                            <span class="separator">|</span>
                            <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder" title="<?php echo $this->__('Reorder') ?>">
                                <span class="fa fa-2x fa-repeat"></span>
                            </a>
                        <?php endif ?>
                        <?php if($_order->hasInvoices()):?>
                            <strong><span>|</span></strong>
                            <strong>
                                <a href="<?php echo $this->getUrl('pdf/index/invoice', array('order_id' => $_order->getId())) ?>" title="<?php echo $this->__('Invoice') ?>">
                                    <span class="fa fa-2x fa-file-pdf-o"></span>
                                </a>
                            </strong>
                        <?php else: ?>
                            <strong><span>|</span></strong>
                            <strong>
                                <span>&nbsp;</span>
                            </strong>
                        <?php endif; ?>
                        </span>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif; ?>
</div>
