<?php
/**
 * Magento e-commerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 *
 * @category   Losreservas1811
 * @package    Losreservas1811_Customer
 * @copyright  Copyright (c) 2018 LOS RESERVAS 1811, SL (https://www.losreservas1811.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 *
 * @category   design
 * @package    base_default/losreservas1811_customer
 * @author     LOS RESERVAS 1811 Team <web@losreservas1811.com>
 */
?>
<?php
/**
 * Customer Account Navigation template
 *
 * @see Mage_Customer_Block_Account_Navigation
 */
?>
<div class="block block-account">
    <div class="block-title">
        <strong><span><?php echo $this->__('My Account'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul>
            <?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); ?>

            <?php $_count = count($_links); /* Add or Remove Account Left Navigation Links Here -*/
                //unset($_links['account']); /* Account Info */
                //unset($_links['account_edit']); /* Account Info */
                //unset($_links['tags']); /* My Tags */
                //unset($_links['invitations']); /* My Invitations */
                //unset($_links['reviews']);  /* Reviews */
                //unset($_links['wishlist']); /* Wishlist */
                //unset($_links['newsletter']); /* Newsletter */
                //unset($_links['orders']); /* My Orders */
                //unset($_links['address_book']); /* Address */
                //unset($_links['enterprise_customerbalance']); /* Store Credit */
                if (array_key_exists('OAuth Customer Tokens', $_links)) {
                    unset($_links['OAuth Customer Tokens']); /* My Applications */
                }
                //unset($_links['enterprise_reward']); /* Reward Points */
                //unset($_links['giftregistry']); /* Gift Registry */
                //unset($_links['downloadable_products']); /* My Downloadable Products */
                if (array_key_exists('recurring_profiles', $_links)) {
                    unset($_links['recurring_profiles']); /* Recurring Profiles */
                }
                if (array_key_exists('billing_agreements', $_links)) {
                    unset($_links['billing_agreements']); /* Billing Agreements */
                }
                //unset($_links['enterprise_giftcardaccount']); /* Gift Card Link */
            ?>

            <?php foreach ($_links as $_link): ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="current<?php echo ($_last ? ' last' : '') ?>"><a href="<?php echo $_link->getUrl() ?>"><strong><?php echo $_link->getLabel() ?></strong></a></li>
                <?php else: ?>
                    <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
